name: diary_app
description: A new Flutter project. diary_app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #firebase :
  #firebase_core là mã chung được yêu cầu cho tất cả các plugin Firebase Flutter.
  firebase_core: ^1.17.1
  #firebase_auth cho phép tích hợp với khả năng Xác thực của Firebase.
  firebase_auth: ^3.3.19
  #cloud_firestore cho phép truy cập vào bộ lưu trữ dữ liệu Cloud Firestore.
  cloud_firestore: ^3.1.17
  #firebase storage to save database:
  firebase_storage: ^10.3.3
  google_sign_in: ^5.3.2
  google_fonts: ^3.0.1
  equatable: ^2.0.0

  rxdart: ^0.27.3
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  font_awesome_flutter: ^10.1.0

  permission_handler: ^10.0.0
  get: ^4.6.5
  image_picker: ^0.8.4+9

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Font Diary
      fonts:
        - asset: assets/fonts/lemonada/Lemonada-Light.ttf
        - asset: assets/fonts/lemonada/Lemonada-Regular.ttf
        - asset: assets/fonts/lemonada/Lemonada-Medium.ttf
        - asset: assets/fonts/lemonada/Lemonada-SemiBold.ttf
        - asset: assets/fonts/lemonada/Lemonada-Bold.ttf

    - family: Font Normally
      fonts:
        - asset: assets/fonts/raleway/Raleway-Thin.ttf
        - asset: assets/fonts/raleway/Raleway-ExtraLight.ttf
        - asset: assets/fonts/raleway/Raleway-Light.ttf
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
        - asset: assets/fonts/raleway/Raleway-ExtraBold.ttf
        - asset: assets/fonts/raleway/Raleway-Black.ttf
        - asset: assets/fonts/raleway/Raleway-ThinItalic.ttf
        - asset: assets/fonts/raleway/Raleway-ExtraLightItalic.ttf
        - asset: assets/fonts/raleway/Raleway-LightItalic.ttf
        - asset: assets/fonts/raleway/Raleway-Italic.ttf
        - asset: assets/fonts/raleway/Raleway-MediumItalic.ttf
        - asset: assets/fonts/raleway/Raleway-SemiBoldItalic.ttf
        - asset: assets/fonts/raleway/Raleway-BoldItalic.ttf
        - asset: assets/fonts/raleway/Raleway-ExtraBoldItalic.ttf
        - asset: assets/fonts/raleway/Raleway-BlackItalic.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
